"""KairosFM: less parameters, more signal."""

from .modeling import KairosConfig, KairosDiffusionFM, KairosMemoryGate, KairosMultiCache, gate_memory_bank
from .pipeline import DataConfig, KairosMultimodalPipeline, TrainConfig
from .tokenizer import KairosTokenizer, Modality

try:
    from ._version import __version__  # generated by setuptools_scm at build
except ImportError:
    __version__ = "0.3.1.dev29"  # editable install with no build

__all__ = [
    "DataConfig",
    "KairosConfig",
    "KairosDiffusionFM",
    "KairosMemoryGate",
    "KairosMultiCache",
    "KairosMultimodalPipeline",
    "KairosTokenizer",
    "Modality",
    "TrainConfig",
    "__version__",
    "gate_memory_bank",
]
