"""Kairos: a hybrid MoE diffusion language model (DeltaNet + sliding-window attention) for multimodal edge AI."""

from .modeling import KairosConfig, KairosDiffusionLLM, KairosMemoryBank
from .pipeline import DataConfig, KairosMultimodalPipeline, TrainConfig
from .tokenizer import KairosTokenizer, Modality

try:
    from ._version import __version__  # generated by setuptools_scm at build time from the git tag
except ImportError:
    __version__ = "0.0.0.dev0"  # editable install with no build step yet run (e.g. `pip install -e .`)

__all__ = [
    "DataConfig",
    "KairosConfig",
    "KairosDiffusionLLM",
    "KairosMemoryBank",
    "KairosMultimodalPipeline",
    "KairosTokenizer",
    "Modality",
    "TrainConfig",
    "__version__",
]
