"""KairosFM: less parameters, more signal."""

from .modeling import KairosConfig, KairosDiffusionLLM, KairosStateCombiner
from .pipeline import DataConfig, KairosMultimodalPipeline, TrainConfig
from .tokenizer import KairosTokenizer, Modality

try:
    from ._version import __version__  # generated by setuptools_scm at build
except ImportError:
    __version__ = "0.0.0.dev0"  # editable install with no build

__all__ = [
    "DataConfig",
    "KairosConfig",
    "KairosDiffusionLLM",
    "KairosMultimodalPipeline",
    "KairosStateCombiner",
    "KairosTokenizer",
    "Modality",
    "TrainConfig",
    "__version__",
]
